### ISSUE TITLE
Picture material on the example scene

### ISSUE THREAD

**Issue by blackorbit1** [DrBlackRat/VRC-Picture-Loader#4]
Hello,
I was experimenting with your prefab and couldn't find a good material parameter combination to get correct white/black/contrasts.
After experimenting other materials, I found out that `VRChat/Sprites/Default` displays the image perfectly.

![39510f11a123b334d02045def85a26e2](https://github.com/DrBlackRat/VRC-Picture-Loader/assets/38140797/177c4c14-6d20-482a-9beb-cbefe4333b1c)

Maybe it could be interesting to either use this material instead in the example scene or mention it in the readme ?

Have a good day !

**Comment by DrBlackRat** [comment]
Interesting idea!
I just used the Standard Material cause... well... it's Standard, and it also represents how the image would look with proper lighting.

I'm not sure if I'm going to change it over, as I try to keep that scene as simple as it can be. ^^

**Comment by DrBlackRat** [comment]
I added it as a tip to the readme ^^
https://github.com/DrBlackRat/VRC-Picture-Loader/commit/6b249bb91eb7e9583d8159fe8627d8c427b985cd
